### ISSUE TITLE
Merge sekoilu

### ISSUE THREAD

**Issue by jhuovari** [pttry/pttrobo#13]
Hmm, sekoitin vissiinkin plot_reworkia main branchiin. En kyllä mielestäni tehnyt merge:ä, mutta niin git väittää. Ajattelin korjata ongelman, vaan poistaa kyseiset tiedostot, mutta @itkonen kai ehti jo muokata ptt_plot_base:a tässä välissä main:ssa, ja poisti ongelman, joka esti lataamisen devtools:lla.
Joten enää toiminnallista ongelmaa ei ole, mutta tiedoksi @krasstek sekoiluni.

**Comment by krasstek** [comment]
Jes huomattiin, huomenna pusken branchista uuden version jossa huomioitu edelliset palautteet ja funktiot integroitu.

**Comment by jhuovari** [comment]
Paitsi, että vuosisumma ei toimi niillä tiedoilla, johon tämä korjaus. Aiemmat vuosisummat toimii.

Miksihän?

Muutos: b0062fef2a9f87e17d4992853fb278bb8178db3e
