### ISSUE TITLE
muodosta_sarjat toistaa tietoja, jos "sisäkkäisiä tasoja"

### ISSUE THREAD

**Issue by jhuovari** [pttry/pttrobo#14]
Esim "tidy/dg_agri" taulussa on samaa kuvaavia ja kategoriaa kuvaavia muuttujia, tällöin "turhat" muuttujat kertaavat tietoja.

Luulen, että jos read_data_yaml.R rivi 121
```
Muuttujat <- setdiff(names(d), "value")
```
perustuisihin yaml:sta luettuihin muuttujiin, ei datan, niin toimisi oikein

**Comment by jhuovari** [comment]
Tämä toikin ongelmia ja luulin, että se liittyy vuosiaggregointiin, mutta tulikin esiin vain tiettyjen datojen vuosiaggregoinnissa.

tidy/US_CommodityPrice_M sisältää Prices Footnote tiedon, jossa on NA tietoja. 
Tällöin vuosiaggregoinnin `tidyr::drop_na() ` tiputtaa kaikki nämä havainnot (read_data_yaml.R r 111).
Mikähän sen tarve oli ja onko idea miten korjata @itkonen ?

**Comment by itkonen** [comment]
tidyr::drop_na()-funktiolle voi syöttää muuttujat, joiden NA-arvot karsivat rivit pois. Eli `tidyr::drop_na(value)` voisi tässä tepsiä? Silloin vain puuttuvan numeroarvon sisältävät rivit karsitaan.

**Comment by jhuovari** [comment]
Totta, muistatko miksi tuo drop_na ylipäätään on?
