### ISSUE TITLE
rangeslide jättää tietoja piiloon

### ISSUE THREAD

**Issue by jhuovari** [pttry/pttrobo#19]
rangeslider toimii nyt hienosti, paitsi

huomasin alla olevalla kuviolla, että euroalueen viimeinen havainto mene y-akselin yläreunasta yli.

ptt_data_robo_c("eurostat/prc_hicp_midx", hash = Sys.time()) |> 
  filter_recode(coicop = "FOOD",
                unit = "I15",
                geo =
                  c(
                    "Euroalue" = "EA", 
                    "Suomi" = "FI"
                    # , 
                    # "Saksa" = "DE",
                    # "Ruotsi" = "SE"
                    )) |>    
  group_by(geo) |> 
  mutate(value = pc(value, 12, time)) |> 
  ungroup() |> 
  # filter(time >= "2017-01-01") |>
  aplot_lines(
    colour = geo,
    title = "Ruuan hinta",
    subtitle = "%, YKHI, vuosimuutos",
    source = "Eurostat, PTT",
    rangeslider = "2017-01-01"
    )

@krasstek

**Comment by krasstek** [comment]
Fiksi ja pushi tehty, y-akselin skaalauksessa tarkasteltiin näkyvän tracen x-akselin rangea ilman yhtäsuuruusmerkkejä, jolloin viimeinen ja ensimmäinen arvo tipahtivat pois.
